In [4]:
import pandas as pd

from nba_api.stats.endpoints import (
    leaguegamefinder,
    leaguedashplayerstats,
    leaguedashteamstats,
    scoreboardv2,
)

pd.set_option("display.max_columns", 100)

SEASON = "2025-26"
SEASON_TYPE = "Regular Season"
PLAYOFF_SEASON_TYPE = "Playoffs"

## Team game logs

In [5]:
team_game_logs_df = leaguegamefinder.LeagueGameFinder(
    player_or_team_abbreviation="T",
    season_nullable=SEASON,
    season_type_nullable=SEASON_TYPE,
).get_data_frames()[0]

team_game_logs_df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22025,1610612760,OKC,Oklahoma City Thunder,0022501196,2026-04-12,OKC vs. PHX,L,240,103,41,95,0.432,18,46,0.391,3,9,0.333,9,27,36,32,9,7,10,8,-32.0
1,22025,1610612765,DET,Detroit Pistons,0022501188,2026-04-12,DET @ IND,W,241,133,50,89,0.562,15,33,0.455,18,22,0.818,12,36,48,35,12,6,17,17,12.0
2,22025,1610612740,NOP,New Orleans Pelicans,0022501195,2026-04-12,NOP @ MIN,L,240,126,45,107,0.421,5,21,0.238,31,38,0.816,20,32,52,20,9,6,9,28,-6.0
3,22025,1610612756,PHX,Phoenix Suns,0022501196,2026-04-12,PHX @ OKC,W,241,135,56,101,0.554,20,41,0.488,3,6,0.500,13,41,54,28,5,8,11,9,32.0
4,22025,1610612743,DEN,Denver Nuggets,0022501197,2026-04-12,DEN @ SAS,W,239,128,50,100,0.500,11,30,0.367,17,22,0.773,19,39,58,30,4,5,10,16,10.0

## Playoff game logs

In [6]:
playoff_game_logs_df = leaguegamefinder.LeagueGameFinder(
    player_or_team_abbreviation="T",
    season_nullable=SEASON,
    season_type_nullable=PLAYOFF_SEASON_TYPE,
).get_data_frames()[0]

playoff_game_logs_df.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42025,1610612752,NYK,New York Knicks,0042500405,2026-06-13,NYK @ SAS,W,240,94,31,87,0.356,12,37,0.324,20,28,0.714,13,35,48,14,8,4,10,21,4.0
1,42025,1610612759,SAS,San Antonio Spurs,0042500405,2026-06-13,SAS vs. NYK,L,240,90,33,86,0.384,12,37,0.324,12,19,0.632,14,33,47,18,6,7,12,22,-4.0
2,42025,1610612752,NYK,New York Knicks,0042500404,2026-06-10,NYK vs. SAS,W,240,107,36,78,0.462,15,32,0.469,20,28,0.714,8,31,39,23,6,4,13,21,1.0
3,42025,1610612759,SAS,San Antonio Spurs,0042500404,2026-06-10,SAS @ NYK,L,239,106,36,86,0.419,17,43,0.395,17,20,0.850,12,30,42,24,10,4,11,21,-1.0
4,42025,1610612752,NYK,New York Knicks,0042500403,2026-06-08,NYK vs. SAS,L,239,111,40,88,0.455,13,37,0.351,18,22,0.818,12,34,46,18,4,6,13,23,-4.0

## Team advanced stats

In [7]:
team_advanced_df = leaguedashteamstats.LeagueDashTeamStats(
    season=SEASON,
    season_type_all_star=SEASON_TYPE,
    measure_type_detailed_defense="Advanced",
    per_mode_detailed="PerGame",
).get_data_frames()[0]

team_advanced_df.head()

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TO,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,OFF_RATING_RANK,DEF_RATING_RANK,NET_RATING_RANK,AST_PCT_RANK,AST_TO_RANK,AST_RATIO_RANK,OREB_PCT_RANK,DREB_PCT_RANK,REB_PCT_RANK,TM_TOV_PCT_RANK,EFG_PCT_RANK,TS_PCT_RANK,PACE_RANK,PIE_RANK
0,1610612737,Atlanta Hawks,82,46,36,0.561,3951.0,113.2,115.0,111.0,112.9,2.3,2.2,0.691,2.13,20.4,0.291,0.702,0.495,0.138,0.554,0.584,104.2,102.50,85.42,8444,0.510,1,11,11,11,14,14,10,12,4,3,2,20,9,17,8,10,12,5,14
1,1610612738,Boston Celtics,82,56,26,0.683,3946.0,116.8,120.0,109.7,111.7,7.1,8.3,0.585,1.99,18.0,0.336,0.710,0.525,0.129,0.553,0.583,97.7,95.58,79.65,7850,0.536,1,4,4,4,26,2,4,4,30,9,22,5,6,3,3,11,13,30,4
2,1610612751,Brooklyn Nets,82,20,62,0.244,3951.0,105.8,108.2,116.0,118.2,-10.2,-10.0,0.668,1.59,18.3,0.287,0.687,0.478,0.161,0.520,0.559,99.6,97.60,81.34,8028,0.436,1,28,28,28,14,30,25,29,8,29,20,21,22,27,29,30,30,26,29
3,1610612766,Charlotte Hornets,82,44,38,0.537,3951.0,114.7,118.4,111.9,113.5,2.9,4.9,0.643,1.71,18.6,0.358,0.722,0.539,0.157,0.552,0.589,99.9,97.59,81.33,8033,0.516,1,16,16,16,14,5,11,8,14,23,16,2,2,2,28,12,10,27,10
4,1610612741,Chicago Bulls,82,31,51,0.378,3951.0,110.5,112.1,115.1,117.4,-4.6,-5.3,0.672,1.86,19.5,0.279,0.708,0.496,0.148,0.547,0.580,105.0,103.22,86.01,8506,0.480,1,22,22,22,14,25,22,23,7,13,8,26,7,16,21,14,16,3,21

## Team base stats

In [ ]:
team_base_df = leaguedashteamstats.LeagueDashTeamStats(
    season=SEASON,
    season_type_all_star=SEASON_TYPE,
    measure_type_detailed_defense="Base",
    per_mode_detailed="PerGame",
).get_data_frames()[0]

team_base_df.head()

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
21,1610612753,Orlando Magic,82,45,37,0.549,48.4,41.0,88.3,0.464,11.7,34.1,0.343,22.0,27.5,0.801,11.0,32.4,43.4,26.5,14.2,8.5,4.7,5.4,21.0,21.9,115.7,0.6,1,13,13,13,6,22,25,21,24,22,27,1,1,8,20,15,19,14,10,16,17,24,25,2,15,17
13,1610612747,Los Angeles Lakers,82,53,29,0.646,48.1,42.0,83.7,0.502,11.8,32.9,0.359,20.4,26.8,0.763,9.4,31.5,41.0,25.9,14.5,8.5,4.3,3.5,18.5,21.0,116.3,1.8,1,6,6,6,29,16,29,1,23,24,14,3,2,26,29,22,27,17,15,14,22,1,3,6,11,14
8,1610612765,Detroit Pistons,82,60,22,0.732,48.3,43.4,89.5,0.485,11.0,30.9,0.356,19.9,26.1,0.763,13.1,32.5,45.6,27.8,15.1,10.4,6.4,5.8,22.0,21.3,117.8,8.2,1,3,3,3,8,5,16,3,28,29,17,7,3,27,3,14,8,11,21,1,1,29,30,4,8,3
6,1610612742,Dallas Mavericks,82,26,56,0.317,48.4,41.9,89.8,0.466,11.0,31.9,0.344,19.5,25.8,0.755,10.5,34.2,44.7,25.3,14.5,7.5,5.2,5.3,18.4,21.0,114.1,-5.5,1,23,23,23,4,17,14,19,29,27,26,10,5,28,22,6,10,22,18,24,10,21,2,5,23,23
7,1610612743,Denver Nuggets,82,54,28,0.659,48.6,43.5,87.8,0.496,14.2,35.8,0.396,20.8,25.8,0.808,9.8,34.2,44.0,29.0,12.9,6.8,4.0,4.6,19.1,21.5,122.1,5.1,1,5,5,5,1,3,26,2,11,20,1,2,4,5,26,5,14,4,3,30,28,13,11,3,1,7

## Player aggregate stats

In [27]:
player_base_df = leaguedashplayerstats.LeagueDashPlayerStats(
    season=SEASON,
    season_type_all_star=SEASON_TYPE,
    measure_type_detailed_defense="Base",
    per_mode_detailed="PerGame",
).get_data_frames()[0]

player_base_df.sort_values(by="GP", ascending=False).head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,WNBA_FANTASY_PTS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
257,1629750,Javonte Green,Javonte,1610612765,DET,32.0,82,60,22,0.732,17.6,2.3,5.0,0.447,1.1,3.0,0.381,1.3,1.5,0.840,0.8,2.0,2.8,0.7,0.5,1.2,0.3,0.2,1.3,1.2,6.9,2.6,15.4,1,0,14.7,1,4,295,65,334,359,349,327,233,255,154,230,259,149,283,325,325,475,424,60,274,395,394,287,327,101,333,201,38,337,1
155,1628978,Donte DiVincenzo,Donte,1610612750,MIN,29.0,82,49,33,0.598,30.4,4.1,10.2,0.406,3.0,7.9,0.379,1.0,1.3,0.743,0.8,3.3,4.1,3.8,1.4,1.3,0.4,0.2,2.4,1.5,12.2,4.1,26.4,1,0,26.5,1,37,135,182,79,183,137,461,17,17,158,307,299,356,259,171,191,83,165,56,195,437,95,233,154,58,134,201,38,122,1
243,1642347,Jamal Shead,Jamal,1610612761,TOR,23.0,82,46,36,0.561,22.6,2.3,6.1,0.367,1.0,3.2,0.321,1.1,1.4,0.784,0.3,1.4,1.7,5.4,1.4,0.9,0.2,0.4,2.0,2.0,6.6,2.8,18.8,2,0,17.0,1,52,102,232,229,359,295,523,263,233,359,269,281,268,480,422,454,42,184,148,380,252,214,160,336,94,258,159,38,279,1
229,1631222,Jake LaRavia,Jake,1610612747,LAL,24.0,82,53,29,0.646,25.1,2.9,6.4,0.459,1.0,3.0,0.321,1.4,1.9,0.763,1.4,2.6,4.0,1.8,1.1,1.3,0.5,0.3,2.4,1.5,8.2,-0.1,19.8,1,0,18.4,1,19,189,132,186,295,286,282,285,261,358,207,214,317,116,254,205,268,245,56,172,289,97,242,274,258,236,201,38,255,1
55,1641764,Brandin Podziemski,Brandin,1610612744,GSW,23.0,82,37,45,0.451,28.4,4.8,10.6,0.455,1.9,5.0,0.371,2.3,2.9,0.797,0.9,4.2,5.1,3.7,1.6,1.1,0.2,0.4,1.7,2.8,13.8,0.2,27.7,5,0,27.0,1,136,36,358,119,137,129,297,110,111,184,106,108,234,233,94,129,88,135,103,380,281,297,86,120,235,123,96,38,118,1

## Daily schedule and standings context

Scoreboard data gives home/away matchups, game status, line scores, series standings during playoffs, and conference standings for a date.

In [ ]:
GAME_DATE = "2026-04-14"

scoreboard = scoreboardv2.ScoreboardV2(game_date=GAME_DATE)
scoreboard_frames = scoreboard.get_data_frames()

game_header_df = scoreboard_frames[0]
line_score_df = scoreboard_frames[1]
series_standings_df = scoreboard_frames[6]
east_standings_df = scoreboard_frames[4]
west_standings_df = scoreboard_frames[5]

game_header_df.head()

/var/folders/22/kxd349s919g7pvnzcyrlx4f00000gn/T/ipykernel_25555/1636230857.py:3: DeprecationWarning: ScoreboardV2 has known issues with line score data for 2025-26 season games (October 22 - December 25, 2025). Please use ScoreboardV3 instead. ScoreboardV3 is fully backward compatible and works for all historical seasons. See: https://github.com/swar/nba_api/issues/596
  scoreboard = scoreboardv2.ScoreboardV2(game_date=GAME_DATE)

,GAME_DATE_EST,GAME_SEQUENCE,GAME_ID,GAME_STATUS_ID,GAME_STATUS_TEXT,GAMECODE,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,LIVE_PERIOD,LIVE_PC_TIME,NATL_TV_BROADCASTER_ABBREVIATION,HOME_TV_BROADCASTER_ABBREVIATION,AWAY_TV_BROADCASTER_ABBREVIATION,LIVE_PERIOD_TIME_BCAST,ARENA_NAME,WH_STATUS,WNBA_COMMISSIONER_FLAG
0,2026-04-15T00:00:00,1,0052500101,3,Final,20260415/ORLPHI,1610612755,1610612753,2025,4,,Amazon,None,None,Q4 - Amazon,Xfinity Mobile Arena,1,0
1,2026-04-15T00:00:00,2,0052500131,3,Final,20260415/GSWLAC,1610612746,1610612744,2025,4,,Amazon,None,None,Q4 - Amazon,Intuit Dome,1,0

In [ ]:
line_score_df.head()

In [ ]:
series_standings_df.head()